[i18n.en]
doctor_validating      = "Doctor: validating configuration..."
base_branch            = "base branch: {branch}"
hooks_file_exists      = "✅ hooks file exists: {path}"
hooks_file_missing     = "❌ hooks file missing: {path}"
todo_file_exists       = "✅ TODO file exists: {path}"
todo_file_missing      = "❌ TODO file missing: {path}"
git_repo_ok            = "✅ git repository: OK"
git_repo_failed        = "❌ git repository check failed: {error}"
todo_ignored_ok        = "✅ TODO file is git-ignored"
todo_not_ignored       = "❌ TODO file is not ignored by git: {path}\n   Please add it to .gitignore (e.g., '/TODO.md') and rerun."
gitignore_check_failed = "❌ Failed to check gitignore: {error}"
doctor_ok              = "✅ Doctor: OK"
doctor_failed          = "❌ Doctor: Failed"
no_todo                = "No TODO items found."
running_parallel       = "Running in worktree-parallel mode with {workers} workers..."
processing             = "Processing: {title}"
pr_created             = "PR created: {url}"
uncommitted_changes    = "Uncommitted changes detected:"
uncommitted_hint       = "Please commit or stash your changes before switching branches."
uncommitted_hint2      = "Hint: git add -A && git commit -m 'WIP'  or  git stash -u"
todo_must_be_ignored   = "TODO file must be ignored by git: {path}\nPlease add it to .gitignore (e.g., '/TODO.md') and rerun."

[i18n.ja]
doctor_validating      = "Doctor: 設定を検証しています..."
base_branch            = "ベースブランチ: {branch}"
hooks_file_exists      = "✅ hooks ファイルがあります: {path}"
hooks_file_missing     = "❌ hooks ファイルが見つかりません: {path}"
todo_file_exists       = "✅ TODO ファイルがあります: {path}"
todo_file_missing      = "❌ TODO ファイルが見つかりません: {path}"
git_repo_ok            = "✅ git リポジトリ: OK"
git_repo_failed        = "❌ git リポジトリ検証に失敗しました: {error}"
todo_ignored_ok        = "✅ TODO ファイルは .gitignore の対象です"
todo_not_ignored       = "❌ TODO ファイルが .gitignore の対象ではありません: {path}\n   .gitignore に追加してください (例: '/TODO.md')。"
gitignore_check_failed = "❌ .gitignore の確認に失敗しました: {error}"
doctor_ok              = "✅ Doctor: OK"
doctor_failed          = "❌ Doctor: 失敗"
no_todo                = "TODO はありません。"
running_parallel       = "worktree 並列モードで実行します (ワーカー: {workers})..."
processing             = "処理中: {title}"
pr_created             = "PR を作成しました: {url}"
uncommitted_changes    = "未コミットの変更が見つかりました:"
uncommitted_hint       = "ブランチ切り替え前にコミットまたはスタッシュしてください。"
uncommitted_hint2      = "ヒント: git add -A && git commit -m 'WIP'  または  git stash -u"
todo_must_be_ignored   = "TODO ファイルは .gitignore の対象である必要があります: {path}\n例: '/TODO.md' を .gitignore に追加してから再実行してください。"
